version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn surefire-report:report
      - mvn verify
  post_build:
    commands:
      - echo Build completed on `date`
reports:
  SurefireReports1:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
  jacoco-report:
    discard-paths: yes
    file-format: JACOCOXML
    base-directory: '/codebuild/output/src090271592/src/github.com/c-umesh/hello-world-aws-cicd/target'
artifacts:
  files:
    - target/messageUtil-1.0.jar

